version: '3.9'

services:
  redis-main:
    image: redis:latest
    container_name: valuator-redis-main
    command: redis-server --requirepass wandersPassword
    ports:
      - "6379:6379"
    networks:
      - app-network
  
  redis-ru:
    image: redis:latest
    container_name: valuator-redis-ru
    command: redis-server --requirepass wandersPassword
    ports:
      - "6380:6379"
    networks:
      - app-network

  redis-eu:
    image: redis:latest
    container_name: valuator-redis-eu
    command: redis-server --requirepass wandersPassword
    ports:
      - "6381:6379"
    networks:
      - app-network

  redis-asia:
    image: redis:latest
    container_name: valuator-redis-asia
    command: redis-server --requirepass wandersPassword
    ports:
      - "6382:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: valuator-rabbitmq
    # для Аутентификация    
    environment:
      - RABBITMQ_DEFAULT_USER=valuator_admin
      - RABBITMQ_DEFAULT_PASS=wandersRabbitPassword
    ports:
      # - "5673:5672"  
      - "15672:15672" # Порт для браузера (админка)
    networks:
      - app-network

  app1:
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    container_name: valuator-app1
    depends_on:
      - redis-main
      - redis-ru
      - redis-eu
      - redis-asia
      - rabbitmq
    environment:
      - DB_MAIN=redis-main:6379,password=wandersPassword
      - DB_RU=redis-ru:6379,password=wandersPassword
      - DB_EU=redis-eu:6379,password=wandersPassword
      - DB_ASIA=redis-asia:6379,password=wandersPassword
      - RabbitMQ_Host=rabbitmq
      - RabbitMQ_User=valuator_admin
      - RabbitMQ_Pass=wandersRabbitPassword
    ports:
      - "5001:8080"
    networks:
      - app-network

  app2:
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    container_name: valuator-app2
    depends_on:
      - redis-main
      - redis-ru
      - redis-eu
      - redis-asia
      - rabbitmq
    environment:
      - DB_MAIN=redis-main:6379,password=wandersPassword
      - DB_RU=redis-ru:6379,password=wandersPassword
      - DB_EU=redis-eu:6379,password=wandersPassword
      - DB_ASIA=redis-asia:6379,password=wandersPassword
      - RabbitMQ_Host=rabbitmq
      - RabbitMQ_User=valuator_admin
      - RabbitMQ_Pass=wandersRabbitPassword
    ports:
      - "5002:8080"
    networks:
      - app-network

  rank-calculator:
    build:
      context: .
      dockerfile: RankCalculator/Dockerfile
    depends_on:
      - redis-main
      - redis-ru
      - redis-eu
      - redis-asia
      - rabbitmq
    environment:
      - DB_MAIN=redis-main:6379,password=wandersPassword
      - DB_RU=redis-ru:6379,password=wandersPassword
      - DB_EU=redis-eu:6379,password=wandersPassword
      - DB_ASIA=redis-asia:6379,password=wandersPassword
      - RABBITMQ_HOST=rabbitmq
      - RabbitMQ_User=valuator_admin
      - RabbitMQ_Pass=wandersRabbitPassword
    networks:
      - app-network
  
  events-logger-1:
    build:
      context: ./EventsLogger
      dockerfile: Dockerfile
    container_name: valuator-event-logger-1
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RabbitMQ_User=valuator_admin
      - RabbitMQ_Pass=wandersRabbitPassword
    networks:
      - app-network

  events-logger-2:
    build:
      context: ./EventsLogger
      dockerfile: Dockerfile
    container_name: valuator-event-logger-2
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RabbitMQ_User=valuator_admin
      - RabbitMQ_Pass=wandersRabbitPassword
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: valuator-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge